name: run-fusesoc-targets
on: [push]

jobs:
  lint-verilator:
    runs-on: ubuntu-latest
    env:
      REPO : gimli
      VLNV : secworks:crypto:gimli
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: gimli
      - run: sudo apt install verilator
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=lint $VLNV
